upgraded spec version and cargo file
DataHighway-DHX/node pull request #204
Opened 2021-06-14 12:54 UTC by ayushmishra2005

2021-06-14 13:07 UTC, cgroeschel approved these changes

2021-06-14 14:06 UTC, ltfschoen commented
looks good, sorry laptop ran out of batteries.
could also update the chain spec and chain definition files in node/chain-built folder, and possibly also add the compiled wasm file in there that we'd use for chain update

2021-06-15 05:43 UTC, ltfschoen requested changes
* [ ] - i'd like to have this PR https://github.com/DataHighway-DHX/node/pull/205 reviewed and merged into this PR
* [ ] - if we or other users aren't able to use the chain specification or chain definition .json files (e.g. chain_def_local.json) that we've included in the chain-built folder, then they should be removed. PR #205 proposes to remove 'dev' and 'local' chain spec and def files
* [x] - it should include an answer to this unanswered question https://github.com/DataHighway-DHX/node/pull/205/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R396 
* [ ] - i'd also like us to try running the Harbour network using five nodes, and confirm that it generates and finalizes blocks, and that another user is able to connect to the running chain by following our documentation, which means that following the steps all these guides should work, otherwise we should update them
https://dev.datahighway.com/docs/en/tutorials/tutorials-nodes-full-node-setup
https://dev.datahighway.com/docs/en/tutorials/tutorials-nodes-validator-setup
https://github.com/DataHighway-DHX/node/blob/master/EXAMPLES.md#testnet-standalone-harbour-pos-with-multiple-nodes-
* [ ] - and we should also try doing this step to check it all works, but only checking that it works on Harbour Testnet instead of Westlake Mainnet https://github.com/DataHighway-DHX/node/blob/master/EXAMPLES.md#mainnet-standalone-westlake-pos-with-multiple-nodes-

2021-06-15 10:29 UTC, ltfschoen approved these changes
propose to merge #204, 
then check that this works on Harbour Testnet

https://github.com/DataHighway-DHX/node/blob/master/EXAMPLES.md#mainnet-standalone-westlake-pos-with-multiple-nodes-

https://dev.datahighway.com/docs/en/tutorials/tutorials-nodes-validator-setup

then release 3.0.5 when confirmed it works, otherwise do any fixes before release

2021-06-15 11:07 UTC, merged